/* eslint-disable max-len */
const planets = {
  en: [
    {
      texture: 'https://i.ibb.co/kmmjDdr/wall.webp',
      title: 'Wallornus',
      description: 'Wallornus is a planet known for its massive walls that stretch across its surface. These walls are made of a mysterious material that is both incredibly durable and resistant to any form of damage.',
      size: '12,000 kilometers in diameter',
      distance: '500 million kilometers from its star',
      gravity: '6.2 m/s²',
      atmosphere: 'Thin and composed mainly of nitrogen and oxygen',
      averageTemperature: '-40 degrees Celsius',
      rotationTime: 'Approximately 24 hours',
      orbitalSpeed: 'About 40,000 kilometers per hour',
      numberofMoons: '3 (Sentinel, Guardian, and Watcher)',
      geographicalFeatures: 'Vast wall formations, towering cliffs, and deep canyons',
      potentialForLife: 'Although there is no evidence of life on Wallornus, some scientists believe that the unique properties of its walls could potentially support the existence of unusual life forms.',
      interestingFacts: 'The walls of Wallornus are covered in ancient inscriptions and symbols that have yet to be deciphered by any known civilization.',
    },
    {
      texture: 'https://i.ibb.co/KybY9Lw/what.webp',
      title: 'Gainys',
      description: 'Gainys is a planet shrouded in mystery, with its entire surface covered in thick fog and mist. The origin and composition of this fog remain unknown, adding to the enigmatic nature of Gainys.',
      size: '10,500 kilometers in diameter',
      distance: '700 million kilometers from its star',
      gravity: '4.9 m/s²',
      atmosphere: 'Primarily composed of water vapor and various gases',
      averageTemperature: '-20 degrees Celsius',
      rotationTime: 'Approximately 36 hours',
      orbitalSpeed: 'About 30,000 kilometers per hour',
      numberofMoons: '1 (Whisper)',
      geographicalFeatures: 'Endless fog-covered plains, hidden valleys, and mysterious floating islands',
      potentialForLife: 'While the dense fog makes it difficult for traditional life forms to survive on Gainys, some scientists speculate that unique organisms capable of thriving in such conditions may exist.',
      interestingFacts: 'Gainys is a popular subject of folklore and legends, with many tales describing hidden treasures and mythical creatures lurking within its misty landscapes.',
    },
    {
      texture: 'https://i.ibb.co/YNJ04KB/granite.jpg',
      title: 'Granitorus',
      description: 'Granitorus is a planet renowned for its vast granite formations that dominate its surface. These massive rock structures, carved by centuries of erosion, create a breathtaking and rugged landscape.',
      size: '15,200 kilometers in diameter',
      distance: '900 million kilometers from its star',
      gravity: '8.5 m/s²',
      atmosphere: 'Thin and composed mainly of nitrogen and trace amounts of oxygen',
      averageTemperature: '-80 degrees Celsius',
      rotationTime: 'Approximately 48 hours',
      orbitalSpeed: 'About 20,000 kilometers per hour',
      numberofMoons: '4 (Titanium, Quartz, Obsidian, and Marble)',
      geographicalFeatures: 'Gigantic granite cliffs, deep canyons, and vast rocky plateaus',
      potentialForLife: 'Although the harsh conditions and lack of organic matter make it unlikely for traditional life forms to exist on Granitorus, scientists speculate that extremophile microorganisms might survive in its rocky environments.',
      interestingFacts: 'Granitorus is a popular destination for rock climbers and adventurers due to its challenging and unique granite formations.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/bambo.avif',
      title: 'Bambolo',
      description: 'Bambolo is a mystical planet covered in dense bamboo forests. Its tranquil atmosphere and serene beauty make it a haven for those seeking peace and harmony.',
      size: '8,000 kilometers in diameter',
      distance: '300 million kilometers from its star',
      gravity: '3.8 m/s²',
      atmosphere: 'Rich in oxygen and carbon dioxide',
      averageTemperature: '30 degrees Celsius',
      rotationTime: 'Approximately 18 hours',
      orbitalSpeed: 'About 60,000 kilometers per hour',
      numberofMoons: '2 (Shaolin and Zen)',
      geographicalFeatures: 'Endless bamboo groves, towering bamboo mountains, and peaceful bamboo gardens',
      potentialForLife: 'Bambolo hosts a diverse ecosystem filled with unique plant and animal species adapted to thrive in bamboo-dominated environments.',
      interestingFacts: 'The bamboo forests of Bambolo are said to possess healing properties, and the planet is famous for its bamboo-based traditional medicine.',
    },
    */
    {
      texture: 'https://i.ibb.co/XtbyMXY/wave.jpg',
      title: 'Wavelen',
      description: 'Wavelen is a water-rich planet entirely covered by vast oceans. Its mesmerizing waves and deep blue beauty attract explorers from across the galaxy.',
      size: '12,000 kilometers in diameter',
      distance: '250 million kilometers from its star',
      gravity: '5.2 m/s²',
      atmosphere: 'Consists mainly of nitrogen and traces of water vapor',
      averageTemperature: '10 degrees Celsius',
      rotationTime: 'Around 30 hours',
      orbitalSpeed: 'Approximately 40,000 kilometers per hour',
      numberofMoons: '1 (Aqua)',
      geographicalFeatures: 'Endless oceanic expanses, towering water spouts, and underwater caves and canyons',
      potentialForLife: 'Wavelen harbors a diverse array of marine life, including sentient aquatic species capable of advanced communication and technology.',
      interestingFacts: 'The waves of Wavelen possess unique properties, creating a harmonious and soothing environment. The planet is a popular destination for water sports and marine research.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/holographic.avif',
      title: 'Holora',
      description: 'Holora is a mesmerizing planet known for its vibrant and ever-changing holographic landscapes. It is an artistic marvel that captivates the imagination.',
      size: '6,500 kilometers in diameter',
      distance: '180 million kilometers from its star',
      gravity: '2.1 m/s²',
      atmosphere: 'Thin, composed of noble gases and holographic particles',
      averageTemperature: '-5 degrees Celsius',
      rotationTime: 'Approximately 24 hours',
      orbitalSpeed: 'Around 70,000 kilometers per hour',
      numberofMoons: '4 (Lumina, Illusion, Mirage, and Phantasma)',
      geographicalFeatures: 'Dazzling holographic forests, ethereal mountains, and shimmering lakes and rivers',
      potentialForLife: 'Holora`s holographic environment offers unique opportunities for life forms capable of manipulating and interacting with holographic projections.',
      interestingFacts: 'Holora`s inhabitants are skilled in the art of holography and use it as a form of communication and artistic expression. The planet hosts spectacular holographic festivals and exhibitions.',
    },
    */
    {
      texture: 'https://i.ibb.co/yWRCFRc/film.jpg',
      title: 'FIlma',
      description: 'Filma is a planet immersed in the magic of storytelling and cinematic wonders. Its landscape resembles the scenes from classic movies, inviting explorers to step into a world of imagination.',
      size: '9,500 kilometers in diameter',
      distance: '400 million kilometers from its star',
      gravity: '4.5 m/s²',
      atmosphere: 'Composed of a mix of gases, including elements of nostalgia and adventure',
      averageTemperature: '20 degrees Celsius',
      rotationTime: 'Around 15 hours',
      orbitalSpeed: 'About 55,000 kilometers per hour',
      numberofMoons: '2 (Reel and Cinema)',
      geographicalFeatures: 'Picturesque film sets, dramatic mountains, and enchanted forests',
      potentialForLife: 'Filma is home to sentient beings who possess incredible storytelling abilities and use their creative skills to shape reality through the power of their imagination.',
      interestingFacts: 'Filma holds a grand film festival where filmmakers from across the galaxy gather to showcase their works. The planet`s landscapes have been featured in numerous iconic movies.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/paper.avif',
      title: 'Paperon',
      description: 'Paperon is an imaginary planet entirely made of paper. It is located in a galaxy known for its creative and imaginative inhabitants who harness the power of paper to build their civilization.',
      size: '5,000 kilometers in diameter',
      distance: '150 million kilometers from its star',
      gravity: '2.5 m/s²',
      atmosphere: 'Thin atmosphere consisting mainly of oxygen and nitrogen',
      averageTemperature: '25 degrees Celsius',
      rotationTime: 'About 12 hours',
      orbitalSpeed: 'About 80,000 kilometers per hour',
      numberofMoons: '3 (Origami, Papyrus, and Scroll)',
      geographicalFeatures: 'Vast forests of paper trees, paper mountains and valleys, and paper-made structures',
      potentialForLife: 'The unique nature of Paperon provides opportunities for organisms capable of utilizing paper-based resources to thrive.',
      interestingFacts: 'Paperon is renowned for its intricate paper art and craftsmanship. Its inhabitants have developed advanced origami techniques and create beautiful paper sculptures.',
    },
    */
    /*
    {
      texture: 'http://127.0.0.1:8000/download/plastic.avif',
      title: 'Plastica',
      description: 'Plastica is a fictional planet entirely made of plastic. It exists in a distant solar system and is home to a society driven by environmental awareness and recycling technology.',
      size: '10,000 kilometers in diameter',
      distance: '500 million kilometers from its star',
      gravity: '5.0 m/s²',
      atmosphere: 'Synthetic air composition with controlled levels of oxygen, nitrogen, and other gases',
      averageTemperature: '30 degrees Celsius',
      rotationTime: 'About 20 hours',
      orbitalSpeed: 'About 70,000 kilometers per hour',
      numberofMoons: '4 (PET, PVC, HDPE, and LDPE)',
      geographicalFeatures: 'Mountain ranges and plains made of various types of plastic, plastic lakes and oceans',
      potentialForLife: 'Plastica`s inhabitants have developed unique ways to recycle and reuse plastic, making it possible for organisms adapted to the plastic environment to thrive.',
      interestingFacts: 'Plastica is known for its advanced recycling technologies and sustainable practices. It serves as a model for other planets on how to manage and reduce plastic waste.',
    },
    */
    {
      texture: 'https://i.ibb.co/DLxtxnH/cheese.jpg',
      title: 'Cheeseum',
      description: 'Cheeseum is a fictional planet made entirely of cheese. It is located in a distant galaxy and is known for its unique culinary delights and cheesy landscapes.',
      size: '8,000 kilometers in diameter',
      distance: '350 million kilometers from its star',
      gravity: '4.2 m/s²',
      atmosphere: 'Cheesy aroma with traces of carbon dioxide',
      averageTemperature: '15 degrees Celsius',
      rotationTime: 'About 18 hours',
      orbitalSpeed: 'About 60,000 kilometers per hour',
      numberofMoons: '5 (Cheddar, Swiss, Gouda, Parmesan, and Blue)',
      geographicalFeatures: 'Hills and valleys made of different types of cheese, cheese rivers and lakes',
      potentialForLife: 'Due to its unique composition, Cheeseum has the potential to support organisms adapted to live in a cheese-rich environment',
      interestingFacts: 'Cheeseum is a favorite destination for intergalactic foodies, offering a wide variety of cheese-based dishes and a Cheese Festival held annually.',
    },
    {
      texture: 'https://i.ibb.co/vvP4R58/2k-sun.jpg',
      title: 'Sun',
      description: 'The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, with internal convective motion that generates a magnetic field via a dynamo process.',
      size: '1.4 million kilometers in diameter',
      distance: '149.6 million kilometers from Earth',
      gravity: '274 m/s²',
      atmosphere: 'Consists mainly of hydrogen and helium',
      averageTemperature: '5,500 degrees Celsius',
      rotationTime: 'About 25 days',
      orbitalSpeed: 'About 220 kilometers per second',
      numberofMoons: '0',
      geographicalFeatures: '???',
      potentialForLife: '???',
      interestingFacts: '???',
    },
    {
      texture: 'https://i.ibb.co/F6jmJ7P/2k-earth-nightmap.jpg',
      title: 'Earth',
      description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 29% of Earth\'s surface is land...',
      size: '12,742 kilometers in diameter',
      distance: '149.6 million kilometers from Sun',
      gravity: '9.8 m/s²',
      atmosphere: 'Consists mainly of nitrogen and oxygen',
      averageTemperature: '15 degrees Celsius',
      rotationTime: 'About 24 hours',
      orbitalSpeed: 'About 107,000 kilometers per hour',
      numberofMoons: '1 (Moon)',
      geographicalFeatures: 'Mountains, valleys, plains, and oceans',
      potentialForLife: 'Earth is the only known planet to support life',
      interestingFacts: 'Earth has a unique system of tectonic plates that cause earthquakes and volcanic activity',
    },
    {
      texture: 'https://i.ibb.co/xYhML7C/2k-moon.jpg',
      title: 'Moon',
      description: 'The Moon is Earth\'s only natural satellite. It is one-quarter the diameter of Earth.',
      size: '3,474 kilometers in diameter',
      distance: '384,400 kilometers from Earth',
      gravity: '1.6 m/s²',
      atmosphere: 'No atmosphere',
      averageTemperature: '-20 degrees Celsius to 20 degrees Celsius',
      rotationTime: 'About 27.3 days',
      orbitalSpeed: 'About 3,683 kilometers per hour',
      numberofMoons: '0',
      geographicalFeatures: 'Craters, mountains, and plains',
      potentialForLife: 'No potential for life due to lack of atmosphere and extreme temperatures',
      interestingFacts: 'The Moon is tidally locked to Earth, meaning it always shows the same face to our planet',
    },
    {
      texture: 'https://i.ibb.co/tKKnFNv/2k-mars.jpg',
      title: 'Mars',
      description: 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, after Mercury. It is often referred to as the "Red Planet" because of its reddish appearance.',
      size: '6,779 kilometers in diameter',
      distance: '227.9 million kilometers from Sun',
      gravity: '3.7 m/s²',
      atmosphere: 'Thin atmosphere consisting mainly of carbon dioxide',
      averageTemperature: '-63 degrees Celsius',
      rotationTime: 'About 24.6 hours',
      orbitalSpeed: 'About 86,677 kilometers per hour',
      numberofMoons: '2 (Phobos and Deimos)',
      geographicalFeatures: 'Large volcanoes, canyons, and polar ice caps',
      potentialForLife: 'Some evidence suggests that Mars may have had conditions suitable for microbial life in the past',
      interestingFacts: 'Mars is home to the tallest volcano and the deepest, longest canyon in the solar system',
    },
  ],

  ru: [
    {
      texture: 'https://i.ibb.co/kmmjDdr/wall.webp',
      title: 'Валлорнус',
      description: 'Валлорнус - планета, известная своими массивными стенами, простирающимися по ее поверхности. Эти стены сделаны из загадочного материала, который одновременно невероятно прочный и устойчивый к любым видам повреждений.',
      size: '12 000 километров в диаметре',
      distance: '500 миллионов километров от своей звезды',
      gravity: '6,2 м/с²',
      atmosphere: 'Тонкая, в основном состоящая из азота и кислорода',
      averageTemperature: '-40 градусов Цельсия',
      rotationTime: 'Примерно 24 часа',
      orbitalSpeed: 'Около 40 000 километров в час',
      numberofMoons: '3 (Страж, Страж и Наблюдатель)',
      geographicalFeatures: 'Обширные образования стен, высокие скалы и глубокие каньоны',
      potentialForLife: 'Хотя нет никаких доказательств жизни на Валлорнусе, некоторые ученые полагают, что уникальные свойства его стен могут потенциально поддерживать существование необычных форм жизни.',
      interestingFacts: 'Стены Валлорнуса покрыты древними надписями и символами, до сих пор не разгаданными никакой известной цивилизацией.',
    },
    {
      texture: 'https://i.ibb.co/KybY9Lw/what.webp',
      title: 'Гайнис',
      description: 'Гайнис - планета, окутанная тайной, с ее поверхностью, покрытой густым туманом и мглой. Происхождение и состав этого тумана остаются неизвестными, что добавляет загадочности Гайнису.',
      size: '10 500 километров в диаметре',
      distance: '700 миллионов километров от своей звезды',
      gravity: '4,9 м/с²',
      atmosphere: 'В основном состоит из водяного пара и различных газов',
      averageTemperature: '-20 градусов Цельсия',
      rotationTime: 'Примерно 36 часов',
      orbitalSpeed: 'Около 30 000 километров в час',
      numberofMoons: '1 (Шептун)',
      geographicalFeatures: 'Бесконечные покрытые туманом равнины, скрытые долины и загадочные плавающие острова',
      potentialForLife: 'Хотя плотный туман делает жизнь традиционных форм сложной на Гайнисе, некоторые ученые полагают, что уникальные организмы, способные приспособиться к таким условиям, могут существовать.',
      interestingFacts: 'Гайнис является популярной темой фольклора и легенд, в которых описываются скрытые сокровища и мифические существа, скрывающиеся среди его туманных ландшафтов.',
    },
    {
      texture: 'https://i.ibb.co/YNJ04KB/granite.jpg',
      title: 'Граниторус',
      description: 'Граниторус - планета, знаменитая своими огромными гранитными образованиями, которые властвуют на ее поверхности. Эти массивные каменные структуры, высеченные веками эрозии, создают впечатляющий и грубый ландшафт.',
      size: '15 200 километров в диаметре',
      distance: '900 миллионов километров от своей звезды',
      gravity: '8,5 м/с²',
      atmosphere: 'Тонкая, в основном состоящая из азота и незначительного количества кислорода',
      averageTemperature: '-80 градусов Цельсия',
      rotationTime: 'Примерно 48 часов',
      orbitalSpeed: 'Около 20 000 километров в час',
      numberofMoons: '4 (Титаниум, Кварц, Обсидиан и Мрамор)',
      geographicalFeatures: 'Гигантские гранитные скалы, глубокие каньоны и обширные каменистые плато',
      potentialForLife: 'Хотя неблагоприятные условия и отсутствие органического вещества делают маловероятным существование традиционных форм жизни на Граниторусе, ученые предполагают, что экстремофильные микроорганизмы могут выживать в его каменистых окружениях.',
      interestingFacts: 'Граниторус является популярным местом для скалолазов и искателей приключений благодаря сложным и уникальным гранитным образованиям.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/bambo.avif',
      title: 'Бамболо',
      description: 'Бамболо - это мистическая планета, покрытая густыми бамбуковыми лесами. Ее спокойная атмосфера и серенадная красота делают ее убежищем для тех, кто ищет мира и гармонии.',
      size: '8 000 километров в диаметре',
      distance: '300 миллионов километров от своей звезды',
      gravity: '3,8 м/с²',
      atmosphere: 'Богатая кислородом и углекислым газом',
      averageTemperature: '30 градусов Цельсия',
      rotationTime: 'Приблизительно 18 часов',
      orbitalSpeed: 'Около 60 000 километров в час',
      numberofMoons: '2 (Шаолинь и Дзен)',
      geographicalFeatures: 'Бесконечные бамбуковые рощи, возвышающиеся бамбуковые горы и мирные бамбуковые сады',
      potentialForLife: 'Бамболо является домом для разнообразной экосистемы, полной уникальных растений и животных, приспособленных к процветанию в бамбуковых средах.',
      interestingFacts: 'Говорят, что бамбуковые леса Бамболо обладают целебными свойствами, и планета известна своей бамбуковой традиционной медициной.',
    },
    */
    {
      texture: 'https://i.ibb.co/XtbyMXY/wave.jpg',
      title: 'Уэйвлен',
      description: 'Уэйвлен - это планета, богатая водой, полностью покрытая огромными океанами. Ее завораживающие волны и глубокая синяя красота привлекают исследователей со всей галактики.',
      size: '12 000 километров в диаметре',
      distance: '250 миллионов километров от своей звезды',
      gravity: '5,2 м/с²',
      atmosphere: 'Состоит в основном из азота и следов водяного пара',
      averageTemperature: '10 градусов Цельсия',
      rotationTime: 'Примерно 30 часов',
      orbitalSpeed: 'Приблизительно 40 000 километров в час',
      numberofMoons: '1 (Аква)',
      geographicalFeatures: 'Бесконечные океанические просторы, возвышающиеся водяные смерчи и подводные пещеры и каньоны',
      potentialForLife: 'Уэйвлен обитает разнообразие морской жизни, включая разумные водные виды, способные к передвижению и использованию передовых средств связи и технологии.',
      interestingFacts: 'Волны Уэйвлен обладают уникальными свойствами, создавая гармоничную и успокаивающую атмосферу. Планета является популярным местом для занятий водными видами спорта и морских исследований.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/holographic.avif',
      title: 'Холора',
      description: 'Холора - это завораживающая планета, известная своими яркими и постоянно меняющимися голографическими пейзажами. Это художественное чудо, которое пленяет воображение.',
      size: '6 500 километров в диаметре',
      distance: '180 миллионов километров от своей звезды',
      gravity: '2,1 м/с²',
      atmosphere: 'Тонкая, состоит из инертных газов и голографических частиц',
      averageTemperature: '-5 градусов Цельсия',
      rotationTime: 'Примерно 24 часа',
      orbitalSpeed: 'Около 70 000 километров в час',
      numberofMoons: '4 (Люмина, Иллюзия, Мираж и Фантазма)',
      geographicalFeatures: 'Ослепительные голографические леса, эфирные горы и мерцающие озера и реки',
      potentialForLife: 'Голографическая среда Холоры предлагает уникальные возможности для форм жизни, способных манипулировать и взаимодействовать с голографическими проекциями.',
      interestingFacts: 'Жители Холоры владеют искусством голографии и используют его как форму общения и художественного выражения. На планете проводятся впечатляющие голографические фестивали и выставки.',
    },
    */
    {
      texture: 'https://i.ibb.co/yWRCFRc/film.jpg',
      title: 'Фильма',
      description: 'Фильма - планета, погруженная в магию рассказов и кинематографических чудес. Ее ландшафт напоминает сцены из классических фильмов, приглашая исследователей вступить в мир воображения.',
      size: '9 500 километров в диаметре',
      distance: '400 миллионов километров от своей звезды',
      gravity: '4,5 м/с²',
      atmosphere: 'Состоит из смеси газов, включая элементы ностальгии и приключений',
      averageTemperature: '20 градусов Цельсия',
      rotationTime: 'Около 15 часов',
      orbitalSpeed: 'Около 55 000 километров в час',
      numberofMoons: '2 (Рил и Синема)',
      geographicalFeatures: 'Живописные киносъемочные площадки, горы и волшебные леса',
      potentialForLife: 'Фильма - дом для разумных существ, обладающих невероятными навыками рассказчиков и использующих свои творческие способности, чтобы формировать реальность с помощью силы своего воображения.',
      interestingFacts: 'На Фильме проходит грандиозный кинофестиваль, где кинематографисты со всей галактики собираются, чтобы показать свои работы. Ландшафты планеты были показаны во многих известных фильмах.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/paper.avif',
      title: 'Паперон',
      description: 'Паперон - вымышленная планета, полностью состоящая из бумаги. Она находится в галактике, известной своими творческими и воображаемыми обитателями, которые используют силу бумаги для построения своей цивилизации.',
      size: '5 000 километров в диаметре',
      distance: '150 миллионов километров от своей звезды',
      gravity: '2,5 м/с²',
      atmosphere: 'Тонкая атмосфера, состоящая в основном из кислорода и азота',
      averageTemperature: '25 градусов Цельсия',
      rotationTime: 'Около 12 часов',
      orbitalSpeed: 'Около 80 000 километров в час',
      numberofMoons: '3 (Оригами, Папирус и Скролл)',
      geographicalFeatures: 'Обширные леса из бумажных деревьев, бумажные горы и долины, а также сооружения из бумаги',
      potentialForLife: 'Уникальная природа Паперона предоставляет возможности для организмов, способных использовать ресурсы на основе бумаги, чтобы процветать.',
      interestingFacts: 'Паперон славится своими сложными бумажными искусствами и мастерством. Его обитатели разработали передовые техники оригами и создают прекрасные бумажные скульптуры.',
    },
    */
    /*
    {
      texture: 'http://127.0.0.1:8000/download/plastic.avif',
      title: 'Пластика',
      description: 'Пластика - вымышленная планета, полностью состоящая из пластика. Она существует в отдаленной солнечной системе и является домом общества, движимого экологическим сознанием и технологиями переработки.',
      size: '10 000 километров в диаметре',
      distance: '500 миллионов километров от своей звезды',
      gravity: '5,0 м/с²',
      atmosphere: 'Синтетический состав воздуха с контролируемым уровнем кислорода, азота и других газов',
      averageTemperature: '30 градусов Цельсия',
      rotationTime: 'Около 20 часов',
      orbitalSpeed: 'Около 70 000 километров в час',
      numberofMoons: '4 (PET, PVC, HDPE и LDPE)',
      geographicalFeatures: 'Горные хребты и равнины из различных видов пластика, пластиковые озера и океаны',
      potentialForLife: 'Обитатели Пластики разработали уникальные способы переработки и повторного использования пластика, что позволяет организмам, приспособленным к пластиковой среде, процветать.',
      interestingFacts: 'Пластика известна своими передовыми технологиями переработки и устойчивыми практиками. Она служит моделью для других планет по управлению и сокращению пластиковых отходов.',
    },
    */
    {
      texture: 'https://i.ibb.co/DLxtxnH/cheese.jpg',
      title: 'Чизиум',
      description: 'Чизиум - вымышленная планета, полностью состоящая из сыра. Она находится в далекой галактике и известна своими уникальными кулинарными изысками и сырными пейзажами.',
      size: '8 000 километров в диаметре',
      distance: '350 миллионов километров от своей звезды',
      gravity: '4,2 м/с²',
      atmosphere: 'Сырный аромат с примесями углекислого газа',
      averageTemperature: '15 градусов Цельсия',
      rotationTime: 'Примерно 18 часов',
      orbitalSpeed: 'Примерно 60 000 километров в час',
      numberofMoons: '5 (Чеддер, Швейцарский, Гауда, Пармезан и Блю)',
      geographicalFeatures: 'Холмы и долины из разных видов сыра, реки и озера из сыра',
      potentialForLife: 'Благодаря своему уникальному составу Чизиум имеет потенциал поддерживать организмы, приспособленные к жизни в сырном окружении',
      interestingFacts: 'Чизиум - излюбленное место для межгалактических гурманов, предлагающее широкий выбор блюд на основе сыра и ежегодный Фестиваль Сыра.',
    },
    {
      texture: 'https://i.ibb.co/vvP4R58/2k-sun.jpg',
      title: 'Солнце',
      description: 'Солнце - звезда в центре Солнечной системы. Оно является практически идеальной сферой горячей плазмы, с внутренним конвективным движением, которое генерирует магнитное поле через динамо-процесс.',
      size: '1,4 миллиона километров в диаметре',
      distance: '149,6 миллионов километров от Земли',
      gravity: '274 м/с²',
      atmosphere: 'Состоит в основном из водорода и гелия',
      averageTemperature: '5 500 градусов Цельсия',
      rotationTime: 'Примерно 25 дней',
      orbitalSpeed: 'Примерно 220 километров в секунду',
      numberofMoons: '0',
      geographicalFeatures: '???',
      potentialForLife: '???',
      interestingFacts: '???',
    },
    {
      texture: 'https://i.ibb.co/F6jmJ7P/2k-earth-nightmap.jpg',
      title: 'Земля',
      description: 'Земля - третья планета от Солнца и единственный астрономический объект, известный как место обитания жизни. Около 29% поверхности Земли составляет суша...',
      size: '12 742 километра в диаметре',
      distance: '149,6 миллионов километров от Солнца',
      gravity: '9,8 м/с²',
      atmosphere: 'Состоит в основном из азота и кислорода',
      averageTemperature: '15 градусов Цельсия',
      rotationTime: 'Примерно 24 часа',
      orbitalSpeed: 'Примерно 107 000 километров в час',
      numberofMoons: '1 (Луна)',
      geographicalFeatures: 'Горы, долины, равнины и океаны',
      potentialForLife: 'Земля - единственная известная планета, поддерживающая жизнь',
      interestingFacts: 'У Земли есть уникальная система тектонических плит, вызывающая землетрясения и вулканическую активность',
    },
    {
      texture: 'https://i.ibb.co/xYhML7C/2k-moon.jpg',
      title: 'Луна',
      description: 'Луна - единственный естественный спутник Земли. Ее диаметр составляет четверть диаметра Земли.',
      size: '3 474 километра в диаметре',
      distance: '384 400 километров от Земли',
      gravity: '1,6 м/с²',
      atmosphere: 'Отсутствует атмосфера',
      averageTemperature: '-20 градусов Цельсия до 20 градусов Цельсия',
      rotationTime: 'Примерно 27,3 дня',
      orbitalSpeed: 'Примерно 3 683 километра в час',
      numberofMoons: '0',
      geographicalFeatures: 'Кратеры, горы и равнины',
      potentialForLife: 'Нет потенциала для жизни из-за отсутствия атмосферы и экстремальных температур',
      interestingFacts: 'Луна прилипла к Земле, что означает, что она всегда показывает одну и ту же сторону нашей планете',
    },
    {
      texture: 'https://i.ibb.co/tKKnFNv/2k-mars.jpg',
      title: 'Марс',
      description: 'Марс - четвертая планета от Солнца и вторая по размеру планета в Солнечной системе после Меркурия. Его часто называют "Красная планета" из-за своего красноватого вида.',
      size: '6 779 километров в диаметре',
      distance: '227,9 миллионов километров от Солнца',
      gravity: '3,7 м/с²',
      atmosphere: 'Тонкая атмосфера, состоящая в основном из углекислого газа',
      averageTemperature: '-63 градуса Цельсия',
      rotationTime: 'Примерно 24,6 часа',
      orbitalSpeed: 'Примерно 86 677 километров в час',
      numberofMoons: '2 (Фобос и Деймос)',
      geographicalFeatures: 'Большие вулканы, каньоны и полярные ледяные шапки',
      potentialForLife: 'Некоторые данные свидетельствуют о том, что в прошлом на Марсе могли быть условия, благоприятные для микробной жизни',
      interestingFacts: 'На Марсе находится самый высокий вулкан и самый глубокий и длинный каньон в Солнечной системе',
    },
  ],
  es: [
    {
      texture: 'https://i.ibb.co/kmmjDdr/wall.webp',
      title: 'Wallornus',
      description: 'Wallornus es un planeta conocido por sus enormes muros que se extienden por toda su superficie. Estas paredes están hechas de un material misterioso que es increíblemente resistente y resistente a cualquier forma de daño.',
      size: '12,000 kilómetros de diámetro',
      distance: '500 millones de kilómetros de su estrella',
      gravity: '6.2 m/s²',
      atmosphere: 'Delgada y compuesta principalmente de nitrógeno y oxígeno',
      averageTemperature: '-40 grados Celsius',
      rotationTime: 'Aproximadamente 24 horas',
      orbitalSpeed: 'Aproximadamente 40,000 kilómetros por hora',
      numberofMoons: '3 (Sentinel, Guardian y Watcher)',
      geographicalFeatures: 'Vastas formaciones de paredes, acantilados imponentes y cañones profundos',
      potentialForLife: 'Aunque no hay evidencia de vida en Wallornus, algunos científicos creen que las propiedades únicas de sus muros podrían soportar la existencia de formas de vida inusuales.',
      interestingFacts: 'Las paredes de Wallornus están cubiertas de inscripciones y símbolos antiguos que aún no han sido descifrados por ninguna civilización conocida.',
    },
    {
      texture: 'https://i.ibb.co/KybY9Lw/what.webp',
      title: 'Gainys',
      description: 'Gainys es un planeta envuelto en misterio, con toda su superficie cubierta de una espesa niebla. El origen y la composición de esta niebla son desconocidos, lo que aumenta la naturaleza enigmática de Gainys.',
      size: '10,500 kilómetros de diámetro',
      distance: '700 millones de kilómetros de su estrella',
      gravity: '4.9 m/s²',
      atmosphere: 'Compuesta principalmente por vapor de agua y diversos gases',
      averageTemperature: '-20 grados Celsius',
      rotationTime: 'Aproximadamente 36 horas',
      orbitalSpeed: 'Aproximadamente 30,000 kilómetros por hora',
      numberofMoons: '1 (Whisper)',
      geographicalFeatures: 'Llanuras interminables cubiertas de niebla, valles ocultos e islas flotantes misteriosas',
      potentialForLife: 'Si bien la densa niebla dificulta que las formas de vida tradicionales sobrevivan en Gainys, algunos científicos especulan que podrían existir organismos únicos capaces de prosperar en tales condiciones.',
      interestingFacts: 'Gainys es un tema popular de folklore y leyendas, con muchos cuentos que describen tesoros ocultos y criaturas míticas acechando en sus paisajes neblinosos.',
    },
    {
      texture: 'https://i.ibb.co/YNJ04KB/granite.jpg',
      title: 'Granitorus',
      description: 'Granitorus es un planeta famoso por sus vastas formaciones de granito que dominan su superficie. Estas enormes estructuras de roca, talladas por siglos de erosión, crean un paisaje impresionante y accidentado.',
      size: '15,200 kilómetros de diámetro',
      distance: '900 millones de kilómetros de su estrella',
      gravity: '8.5 m/s²',
      atmosphere: 'Delgada y compuesta principalmente de nitrógeno y pequeñas cantidades de oxígeno',
      averageTemperature: '-80 grados Celsius',
      rotationTime: 'Aproximadamente 48 horas',
      orbitalSpeed: 'Aproximadamente 20,000 kilómetros por hora',
      numberofMoons: '4 (Titanium, Quartz, Obsidian y Marble)',
      geographicalFeatures: 'Acantilados de granito gigantes, cañones profundos y vastos mesetas rocosas',
      potentialForLife: 'Aunque las condiciones severas y la falta de materia orgánica hacen que sea poco probable que existan formas de vida tradicionales en Granitorus, los científicos especulan que los microorganismos extremófilos podrían sobrevivir en sus entornos rocosos.',
      interestingFacts: 'Granitorus es un destino popular para escaladores y aventureros debido a sus desafiantes y únicas formaciones de granito.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/bambo.avif',
      title: 'Bambolo',
      description: 'Bambolo es un planeta místico cubierto de densos bosques de bambú. Su atmósfera tranquila y su belleza serena lo convierten en un refugio para aquellos que buscan paz y armonía.',
      size: '8,000 kilómetros de diámetro',
      distance: '300 millones de kilómetros de su estrella',
      gravity: '3.8 m/s²',
      atmosphere: 'Rica en oxígeno y dióxido de carbono',
      averageTemperature: '30 grados Celsius',
      rotationTime: 'Aproximadamente 18 horas',
      orbitalSpeed: 'Aproximadamente 60,000 kilómetros por hora',
      numberofMoons: '2 (Shaolin y Zen)',
      geographicalFeatures: 'Bambú interminable, montañas de bambú imponentes y jardines de bambú pacíficos',
      potentialForLife: 'Bambolo alberga un ecosistema diverso lleno de especies de plantas y animales únicos adaptados para prosperar en entornos dominados por el bambú.',
      interestingFacts: 'Se dice que los bosques de bambú de Bambolo tienen propiedades curativas, y el planeta es famoso por su medicina tradicional a base de bambú.',
    },
    */
    {
      texture: 'https://i.ibb.co/XtbyMXY/wave.jpg',
      title: 'Wavelen',
      description: 'Wavelen es un planeta rico en agua cubierto por vastos océanos. Sus olas hipnóticas y su belleza azul profundo atraen a exploradores de toda la galaxia.',
      size: '12,000 kilómetros de diámetro',
      distance: '250 millones de kilómetros de su estrella',
      gravity: '5.2 m/s²',
      atmosphere: 'Compuesta principalmente de nitrógeno y trazas de vapor de agua',
      averageTemperature: '10 grados Celsius',
      rotationTime: 'Aproximadamente 30 horas',
      orbitalSpeed: 'Aproximadamente 40,000 kilómetros por hora',
      numberofMoons: '1 (Aqua)',
      geographicalFeatures: 'Expansiones oceánicas interminables, torres de agua imponentes y cuevas y cañones submarinos',
      potentialForLife: 'Wavelen alberga una amplia variedad de vida marina, incluidas especies acuáticas conscientes capaces de comunicación y tecnología avanzadas.',
      interestingFacts: 'Las olas de Wavelen poseen propiedades únicas, creando un entorno armonioso y relajante. El planeta es un destino popular para deportes acuáticos e investigaciones marinas.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/holographic.avif',
      title: 'Holora',
      description: 'Holora es un planeta fascinante conocido por sus paisajes holográficos vibrantes y cambiantes. Es una maravilla artística que cautiva la imaginación.',
      size: '6,500 kilómetros de diámetro',
      distance: '180 millones de kilómetros de su estrella',
      gravity: '2.1 m/s²',
      atmosphere: 'Delgada, compuesta por gases nobles y partículas holográficas',
      averageTemperature: '-5 grados Celsius',
      rotationTime: 'Aproximadamente 24 horas',
      orbitalSpeed: 'Alrededor de 70,000 kilómetros por hora',
      numberofMoons: '4 (Lumina, Illusion, Mirage y Phantasma)',
      geographicalFeatures: 'Bosques holográficos deslumbrantes, montañas etéreas y lagos y ríos brillantes',
      potentialForLife: 'El entorno holográfico de Holora ofrece oportunidades únicas para formas de vida capaces de manipular e interactuar con proyecciones holográficas.',
      interestingFacts: 'Los habitantes de Holora son expertos en el arte de la holografía y lo utilizan como forma de comunicación y expresión artística. El planeta acoge festivales y exposiciones holográficas espectaculares.',
    },
    */
    {
      texture: 'https://i.ibb.co/yWRCFRc/film.jpg',
      title: 'FIlma',
      description: 'Filma es un planeta inmerso en la magia de la narración y las maravillas cinematográficas. Su paisaje se asemeja a las escenas de películas clásicas, invitando a los exploradores a adentrarse en un mundo de imaginación.',
      size: '9,500 kilómetros de diámetro',
      distance: '400 millones de kilómetros de su estrella',
      gravity: '4.5 m/s²',
      atmosphere: 'Compuesta por una mezcla de gases, incluyendo elementos de nostalgia y aventura',
      averageTemperature: '20 grados Celsius',
      rotationTime: 'Aproximadamente 15 horas',
      orbitalSpeed: 'Aproximadamente 55,000 kilómetros por hora',
      numberofMoons: '2 (Reel y Cinema)',
      geographicalFeatures: 'Paisajes pintorescos de escenarios de cine, montañas dramáticas y bosques encantados',
      potentialForLife: 'Filma es hogar de seres conscientes que poseen habilidades increíbles para contar historias y utilizan sus habilidades creativas para dar forma a la realidad a través del poder de su imaginación.',
      interestingFacts: 'Filma alberga un gran festival de cine donde cineastas de toda la galaxia se reúnen para exhibir sus obras. Los paisajes del planeta han sido presentados en numerosas películas icónicas.',
    },
    /*
    {
      texture: 'http://127.0.0.1:8000/download/paper.avif',
      title: 'Paperon',
      description: 'Paperon es un planeta imaginario hecho completamente de papel. Se encuentra en una galaxia conocida por sus habitantes creativos e imaginativos que aprovechan el poder del papel para construir su civilización.',
      size: '5,000 kilómetros de diámetro',
      distance: '150 millones de kilómetros de su estrella',
      gravity: '2.5 m/s²',
      atmosphere: 'Atmósfera tenue compuesta principalmente de oxígeno y nitrógeno',
      averageTemperature: '25 grados Celsius',
      rotationTime: 'Aproximadamente 12 horas',
      orbitalSpeed: 'Aproximadamente 80,000 kilómetros por hora',
      numberofMoons: '3 (Origami, Papiro y Pergamino)',
      geographicalFeatures: 'Vastos bosques de árboles de papel, montañas y valles de papel, y estructuras hechas de papel',
      potentialForLife: 'La naturaleza única de Paperon brinda oportunidades para organismos capaces de utilizar recursos basados en papel para prosperar.',
      interestingFacts: 'Paperon es famoso por su intrincada arte del papel y su artesanía. Sus habitantes han desarrollado técnicas avanzadas de origami y crean hermosas esculturas de papel.',
    },
    */
    /*
    {
      texture: 'http://127.0.0.1:8000/download/plastic.avif',
      title: 'Plastica',
      description: 'Plastica es un planeta ficticio hecho completamente de plástico. Existe en un sistema solar distante y es hogar de una sociedad impulsada por la conciencia ambiental y la tecnología de reciclaje.',
      size: '10,000 kilómetros de diámetro',
      distance: '500 millones de kilómetros de su estrella',
      gravity: '5.0 m/s²',
      atmosphere: 'Composición de aire sintético con niveles controlados de oxígeno, nitrógeno y otros gases',
      averageTemperature: '30 grados Celsius',
      rotationTime: 'Aproximadamente 20 horas',
      orbitalSpeed: 'Aproximadamente 70,000 kilómetros por hora',
      numberofMoons: '4 (PET, PVC, HDPE y LDPE)',
      geographicalFeatures: 'Cadenas montañosas y llanuras hechas de varios tipos de plástico, lagos y océanos de plástico',
      potentialForLife: 'Los habitantes de Plastica han desarrollado formas únicas de reciclar y reutilizar plástico, lo que permite que los organismos adaptados al entorno de plástico prosperen.',
      interestingFacts: 'Plastica es conocida por sus tecnologías avanzadas de reciclaje y prácticas sostenibles. Sirve como modelo para otros planetas sobre cómo gestionar y reducir los desechos plásticos.',
    },
    */
    {
      texture: 'https://i.ibb.co/DLxtxnH/cheese.jpg',
      title: 'Cheeseum',
      description: 'Cheeseum es un planeta ficticio hecho completamente de queso. Se encuentra en una galaxia lejana y es conocido por sus delicias culinarias únicas y sus paisajes quesosos.',
      size: '8,000 kilómetros de diámetro',
      distance: '350 millones de kilómetros de su estrella',
      gravity: '4.2 m/s²',
      atmosphere: 'Aroma quesoso con trazas de dióxido de carbono',
      averageTemperature: '15 grados Celsius',
      rotationTime: 'Aproximadamente 18 horas',
      orbitalSpeed: 'Aproximadamente 60,000 kilómetros por hora',
      numberofMoons: '5 (Cheddar, Suizo, Gouda, Parmesano y Azul)',
      geographicalFeatures: 'Colinas y valles hechos de diferentes tipos de queso, ríos y lagos de queso',
      potentialForLife: 'Debido a su composición única, Cheeseum tiene el potencial de albergar organismos adaptados a vivir en un entorno rico en queso.',
      interestingFacts: 'Cheeseum es un destino favorito para los amantes de la comida intergaláctica, ya que ofrece una amplia variedad de platos basados en queso y un Festival del Queso que se celebra anualmente.',
    },
    {
      texture: 'https://i.ibb.co/vvP4R58/2k-sun.jpg',
      title: 'Sol',
      description: 'El Sol es la estrella en el centro del Sistema Solar. Es una esfera casi perfecta de plasma caliente, con un movimiento convectivo interno que genera un campo magnético a través de un proceso de dínamo.',
      size: '1.4 millones de kilómetros de diámetro',
      distance: '149.6 millones de kilómetros de la Tierra',
      gravity: '274 m/s²',
      atmosphere: 'Compuesta principalmente de hidrógeno y helio',
      averageTemperature: '5,500 grados Celsius',
      rotationTime: 'Aproximadamente 25 días',
      orbitalSpeed: 'Aproximadamente 220 kilómetros por segundo',
      numberofMoons: '0',
      geographicalFeatures: '???',
      potentialForLife: '???',
      interestingFacts: '???',
    },
    {
      texture: 'https://i.ibb.co/F6jmJ7P/2k-earth-nightmap.jpg',
      title: 'Tierra',
      description: 'La Tierra es el tercer planeta desde el Sol y el único objeto astronómico conocido que alberga vida. Aproximadamente el 29% de la superficie de la Tierra es tierra...',
      size: '12,742 kilómetros de diámetro',
      distance: '149.6 millones de kilómetros desde el Sol',
      gravity: '9.8 m/s²',
      atmosphere: 'Compuesta principalmente de nitrógeno y oxígeno',
      averageTemperature: '15 grados Celsius',
      rotationTime: 'Aproximadamente 24 horas',
      orbitalSpeed: 'Aproximadamente 107,000 kilómetros por hora',
      numberofMoons: '1 (Luna)',
      geographicalFeatures: 'Montañas, valles, llanuras y océanos',
      potentialForLife: 'La Tierra es el único planeta conocido que soporta vida',
      interestingFacts: 'La Tierra tiene un sistema único de placas tectónicas que causan terremotos y actividad volcánica',
    },
    {
      texture: 'https://i.ibb.co/xYhML7C/2k-moon.jpg',
      title: 'Luna',
      description: 'La Luna es el único satélite natural de la Tierra. Tiene una cuarta parte del diámetro de la Tierra.',
      size: '3,474 kilómetros de diámetro',
      distance: '384,400 kilómetros de la Tierra',
      gravity: '1.6 m/s²',
      atmosphere: 'Sin atmósfera',
      averageTemperature: 'De -20 grados Celsius a 20 grados Celsius',
      rotationTime: 'Aproximadamente 27.3 días',
      orbitalSpeed: 'Aproximadamente 3,683 kilómetros por hora',
      numberofMoons: '0',
      geographicalFeatures: 'Cráteres, montañas y llanuras',
      potentialForLife: 'Sin potencial para vida debido a la falta de atmósfera y las temperaturas extremas',
      interestingFacts: 'La Luna está bloqueada gravitacionalmente a la Tierra, lo que significa que siempre muestra la misma cara a nuestro planeta',
    },
    {
      texture: 'https://i.ibb.co/tKKnFNv/2k-mars.jpg',
      title: 'Marte',
      description: 'Marte es el cuarto planeta desde el Sol y el segundo planeta más pequeño del Sistema Solar, después de Mercurio. A menudo se le llama el "Planeta Rojo" debido a su apariencia rojiza.',
      size: '6,779 kilómetros de diámetro',
      distance: '227.9 millones de kilómetros desde el Sol',
      gravity: '3.7 m/s²',
      atmosphere: 'Atmósfera delgada compuesta principalmente de dióxido de carbono',
      averageTemperature: '-63 grados Celsius',
      rotationTime: 'Aproximadamente 24.6 horas',
      orbitalSpeed: 'Aproximadamente 86,677 kilómetros por hora',
      numberofMoons: '2 (Fobos y Deimos)',
      geographicalFeatures: 'Grandes volcanes, cañones y casquetes polares de hielo',
      potentialForLife: 'Algunas evidencias sugieren que Marte pudo haber tenido condiciones adecuadas para la vida microbiana en el pasado',
      interestingFacts: 'Marte alberga el volcán más alto y el cañón más profundo y más largo del sistema solar',
    },
  ],
};

export default planets;
